apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: my-backend-image:latest
          ports:
            - containerPort: 3001
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_URL
              value: "redis://redis-service:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001 # Added nodePort for external access
  type: NodePort
